name : generate ascii artwork

on: push

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      
      steps:
      - name:  checkout repo
        uses: actions/checkout@v5

      - name : list repo files
        run: ls -ltra

      - name: shell script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh


