name : generate ascii artwork

on: push

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      
      steps:
      - name:  checkout repo
        uses: actions/checkout@v5

      - name: shell script
        run: ./ascii-script.sh


